[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@ds-test/=lib/ds-test/src/",
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    "@oz/=lib/oz/contracts/"
]
rpc_endpoints = { hyperspace = '${HYPERSPACE_RPC_URL}' }
chain_id = 3141
fuzz_runs = 256
optimizer = true

[profile.default.optimizer_details]
yul = false
